version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001" 
    volumes:
      - /usr/src/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"   
    depends_on:
      - db
    volumes:
      - /home/src/backend
      
  db:
    image: postgres
    container_name: $DOCKER_DB_CONTAINER_NAME
    ports:
      - "8080:5432"  
    environment:
      POSTGRES_PASSWORD: $DOCKER_DB_PASSWORD
      POSTGRES_DB: $DOCKER_DB_NAME
      POSTGRES_USER: $DOCKER_DB_USER
    volumes:
      - ./postgres:/var/lib/postgres

  

    
